<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'The verification code is incorrect.' => 'O código de verificação está incorreto.',
    '"secret" param is required.' => 'o parâmetro "segredo" é obrigatório.',
    'Wrong theme value "{value}". Only "dark" and "light" are allowed.' => 'Valor incorreto do tema "{value}". Só é permitido "dark" e "light".',
    'Wrong type value "{value}". Only "image" and "audio" are allowed.' => 'Valor incorreto de tipo "{value}". Só é permitido "image" e "audio".',
    'Wrong size value "{value}". Only "compact" and "normal" are allowed.' => 'Valor incorreto de tamanho "{value}". Só é permitido "compact" e "normal".',
];
