language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install:
    - composer install

script:
    - vendor/bin/phpcs --standard=vendor/yiisoft/yii2-coding-standards/Yii2 --extensions=php src
    - php vendor/bin/codecept run --coverage --coverage-xml
