<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'The verification code is incorrect.' => 'El código de verificación es incorrecto.',
    '"secret" param is required.' => 'se requiere el parámetro "secreto".',
    'Wrong theme value "{value}". Only "dark" and "light" are allowed.' => 'Valor incorrecto "{value}" para el tema. Solo se permiten "dark" y "light".',
    'Wrong type value "{value}". Only "image" and "audio" are allowed.' => 'Valor de tipo incorrecto "{value}". Solo se permiten "image" y "audio".',
    'Wrong size value "{value}". Only "compact" and "normal" are allowed.' => 'Valor de tamaño incorrecto "{valor}". Solo se permiten "compact" y "normal".',
];
